#!/usr/bin/env python3
"""Generate the sample library's systems from NeoStation's own system definitions.

Each system is `assets/systems/<id>.json` in the source. What the systems screen reads from one is
its name and short name, its two colours, and the release date, manufacturer and type the sort
orders use (`lib/services/json_config_service.dart:91-121`). They are copied here rather than
transcribed, so a card's tint and a sort's order are the source's.

Which systems: the ones `site-03.webp` shows, in the order it shows them, then the common consoles
and handhelds, and CPS1 and CPS2 for `site-04.webp` and `site-06.webp`. A system's game count is
not here: it is the length of its sample list in `games.ts`.

Usage, from the repo root:
    python3 docs/themes/neostation/reference/extract-systems.py \\
        <neostation-frontend> > app/src/themes/neostation/systems.ts
"""
import json
import sys
from pathlib import Path

root = Path(sys.argv[1])

# The virtual systems, then the real ones, with a sample game count each. `android` exists only
# on Android (`lib/repositories/system_repository.dart:62-65`); the count is its apps.
SYSTEMS = [
    "all", "favorites", "android",
    "arc", "chf", "a2", "2600", "mo2", "vc4k", "a2001", "cv", "vect", "msx", "nes", "sms", "pce", "7800",
    "genesis", "gb", "lynx", "snes", "gg", "ngp", "n64", "ps1", "gbc", "ngpc", "ws", "dc", "gba", "ds",
    "psp", "cps1", "cps2",
]

logos = {p.stem for p in (root / "assets/images/logos").glob("*.webp")}

out = [
    "/**",
    " * The sample library's systems, from NeoStation's `assets/systems/*.json`. Generated by",
    " * `docs/themes/neostation/reference/extract-systems.py`; do not edit by hand. `roms` is the",
    " * mockup's sample count, not the source's.",
    " */",
    "export interface SystemDef {",
    "  readonly id: string",
    "  readonly name: string",
    "  readonly short: string",
    "  /** `colors[0]`, the card's tint. */",
    "  readonly color1: string | null",
    "  readonly color2: string | null",
    "  readonly released: string",
    "  readonly manufacturer: string",
    "  readonly type: string",
    "  /** `assets/images/logos/<id>.webp` exists; without it the card falls back to text. */",
    "  readonly logo: boolean",
    "  /** Has a RetroAchievements id: the details card gets an achievements tab. */",
    "  readonly ra: boolean",
    "  /** The Emulators tab's rows per platform: RetroArch groups, then standalones, in the JSON's order. */",
    "  readonly emulators: { readonly android: Emulators; readonly linux: Emulators }",
    "}",
    "",
    "export interface Emulators {",
    "  readonly groups: readonly string[]",
    "  readonly standalone: readonly string[]",
    "  /** Every emulator by its JSON name, cores ungrouped - the game settings dialog's rows. */",
    "  readonly all: readonly string[]",
    "}",
    "",
    "export const SYSTEM_DEFS: readonly SystemDef[] = [",
]
def ra(s):
    """`game_details_card_list.dart:330-333`: a non-empty, non-"0" RetroAchievements id."""
    v = (s.get("ids") or {}).get("retroachievements")
    return v not in (None, "", 0, "0")


def emulators(doc, platform):
    """`system_emulator_settings_dialog.dart:640-720`: RetroArch cores grouped by package, first seen
    first - by `unique_id` on Android, one unified group elsewhere - then the standalones."""
    groups, standalone, every = [], [], []
    for e in doc.get("emulators", []):
        if platform not in (e.get("platforms") or {}):
            continue
        every.append(e["name"])
        uid = e.get("unique_id", "")
        if e["name"].startswith("RetroArch"):
            if platform == "android":
                g = "RetroArch 64" if ".ra64." in uid else "RetroArch 32" if ".ra32." in uid else "RetroArch"
            else:
                g = "RetroArch"
            if g not in groups:
                groups.append(g)
        else:
            standalone.append(e["name"])
    return f"{{ groups: {json.dumps(groups)}, standalone: {json.dumps(standalone)}, all: {json.dumps(every)} }}"


for sid in SYSTEMS:
    doc = json.loads((root / f"assets/systems/{sid}.json").read_text())
    s = doc["system"]
    d = s.get("details", {})
    colors = s.get("colors", [])
    c1 = json.dumps(colors[0].lower()) if len(colors) > 0 else "null"
    c2 = json.dumps(colors[1].lower()) if len(colors) > 1 else "null"
    out.append(
        "  { "
        f"id: {json.dumps(s['id'])}, name: {json.dumps(s['name'])}, short: {json.dumps(s.get('short_name') or s['name'])}, "
        f"color1: {c1}, color2: {c2}, released: {json.dumps(d.get('release_date', ''))}, "
        f"manufacturer: {json.dumps(d.get('manufacturer', ''))}, type: {json.dumps(d.get('type', ''))}, "
        f"logo: {'true' if s['id'] in logos else 'false'}, ra: {'true' if ra(s) else 'false'}, "
        f"emulators: {{ android: {emulators(doc, 'android')}, linux: {emulators(doc, 'linux')} }} "
        "},"
    )
out.append("]")
print("\n".join(out))
