#!/usr/bin/env python3
"""Build the two Material Symbols fonts NeoStation draws its icons in, cut down to what it uses.

NeoStation's icons are `Symbols.<name>` from `material_symbols_icons` 4.2960.0: `<name>_rounded`
from the Rounded family, and a bare `<name>` from Outlined. `lib/main.dart:1076` sets
`IconThemeData(fill: 1.0)`, so every one of them is drawn filled. The variable fonts are 10-15MB
each; this pins them at FILL 1, weight 400, grade 0, optical size 24 and keeps only the glyphs the
source names, which is what the mockup ships.

Run in a container with fontTools, from the repo root:

    docker run --rm -v "$PWD":/w -w /w python:3.12-slim sh -c \\
      'pip -q install fonttools brotli && python docs/themes/neostation/reference/subset-symbols.py \\
       <neostation-frontend>/lib tmp/claude/symbols app/src/themes/neostation/assets/fonts'

The second argument holds `Rounded.ttf`, `Outlined.ttf` and their `.codepoints`, from
google/material-design-icons `variablefont/`. It also writes `symbols.ts`, the name-to-codepoint
table the views draw from.
"""
import re
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

lib, src, out = (Path(a) for a in sys.argv[1:4])

used = set()
for f in lib.rglob("*.dart"):
    used.update(re.findall(r"Symbols\.([a-z0-9_]+)", f.read_text(errors="ignore")))

families = {"Rounded": sorted(n[: -len("_rounded")] for n in used if n.endswith("_rounded")),
            "Outlined": sorted(n for n in used if not n.endswith("_rounded"))}

table = {}
for fam, names in families.items():
    points = dict(line.split() for line in (src / f"{fam}.codepoints").read_text().splitlines() if line.strip())
    missing = [n for n in names if n not in points]
    if missing:
        raise SystemExit(f"{fam}: not in the font: {missing}")
    font = TTFont(src / f"{fam}.ttf")
    font = instancer.instantiateVariableFont(font, {"FILL": 1, "wght": 400, "GRAD": 0, "opsz": 24})
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = []
    opts.name_IDs = ["*"]
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=[int(points[n], 16) for n in names])
    sub.subset(font)
    font.flavor = "woff2"
    font.save(out / f"MaterialSymbols{fam}-subset.woff2")
    for n in names:
        key = n + "_rounded" if fam == "Rounded" else n
        table[key] = (fam, int(points[n], 16))

# The few icons the source draws with `fill: 0` against the app-wide 1: the details footer's
# action circles when off (`game_details_footer.dart:767`), its clock (`:1054`), and RomM's
# cloud-sync toggle when off (`romm_browse_screen.dart:1123`).
UNFILLED = ["casino", "favorite", "settings", "schedule", "cloud_sync"]
points = dict(line.split() for line in (src / "Rounded.codepoints").read_text().splitlines() if line.strip())
font = TTFont(src / "Rounded.ttf")
font = instancer.instantiateVariableFont(font, {"FILL": 0, "wght": 400, "GRAD": 0, "opsz": 24})
opts = subset.Options()
opts.flavor = "woff2"
opts.layout_features = []
opts.name_IDs = ["*"]
sub = subset.Subsetter(opts)
sub.populate(unicodes=[int(points[n], 16) for n in UNFILLED])
sub.subset(font)
font.flavor = "woff2"
font.save(out / "MaterialSymbolsRounded-unfilled-subset.woff2")

lines = [
    "/**",
    " * Every `Symbols.<name>` NeoStation's source uses, and where it sits in the subset fonts. Generated by",
    " * `docs/themes/neostation/reference/subset-symbols.py`; do not edit by hand.",
    " */",
    "export const SYMBOLS = {",
]
for key in sorted(table):
    fam, cp = table[key]
    lines.append(f"  {key}: {{ family: '{fam.lower()}', cp: 0x{cp:x} }},")
lines.append("} as const")
lines.append("")
lines.append("export type SymbolName = keyof typeof SYMBOLS")
lines.append("")
lines.append("/** Symbols the source also draws unfilled; the rest exist only filled. */")
lines.append("export const UNFILLED: readonly SymbolName[] = [" + ", ".join(f"'{n}_rounded'" for n in UNFILLED) + "]")
(out.parent.parent / "symbols.ts").write_text("\n".join(lines) + "\n")
print(f"rounded {len(families['Rounded'])}, outlined {len(families['Outlined'])}")
