/**
 * The sample library, lifted from the original by `scripts/gen-psx-data.mjs`.
 *
 * Generated, so it is not edited by hand - re-run the script instead. The types and the
 * predicates that read it live in `library.ts`.
 */
import type { PsxGame, PsxSystem } from './library'

export const SYSTEMS: readonly PsxSystem[] = [
  {
    theme: "psx",
    name: "psx",
    fullName: "Sony PlayStation",
    manufacturer: "Sony",
    hardwareType: "Console",
    releaseYear: 1994,
    total: 66,
    favorites: 16,
    gamesPlayed: 27,
    mostPlayed: "Final Fantasy VII",
    description: "The PlayStation is a 32-bit fifth-generation home video game console released by Sony in 1994. It was the first console to ship 100 million units and made CD-ROM the dominant game medium.",
    linea: [
      "#F2001A",
      "#00AD9E"
    ],
    hasConsole: true,
    hasLogo: true
  },
  {
    theme: "snes",
    name: "snes",
    fullName: "Super Nintendo",
    manufacturer: "Nintendo",
    hardwareType: "Console",
    releaseYear: 1990,
    total: 48,
    favorites: 9,
    gamesPlayed: 21,
    mostPlayed: "Super Metroid",
    description: "The Super Nintendo Entertainment System is a 16-bit console released by Nintendo in 1990, and the best-selling console of its generation.",
    linea: [
      "#7B68C4",
      "#E5E5E5"
    ],
    hasConsole: true,
    hasLogo: true
  },
  {
    theme: "n64",
    name: "n64",
    fullName: "Nintendo 64",
    manufacturer: "Nintendo",
    hardwareType: "Console",
    releaseYear: 1996,
    total: 31,
    favorites: 7,
    gamesPlayed: 14,
    mostPlayed: "GoldenEye 007",
    description: "The Nintendo 64 is a 64-bit console released in 1996, named for its 64-bit processor and remembered for bringing analogue 3D control to the mainstream.",
    linea: [
      "#009B48",
      "#F5C400"
    ],
    hasConsole: true,
    hasLogo: true
  },
  {
    theme: "megadrive",
    name: "megadrive",
    fullName: "Sega Mega Drive",
    manufacturer: "Sega",
    hardwareType: "Console",
    releaseYear: 1988,
    total: 54,
    favorites: 12,
    gamesPlayed: 19,
    mostPlayed: "Sonic the Hedgehog 2",
    description: "The Mega Drive is a 16-bit console released by Sega in 1988, sold as the Genesis in North America.",
    linea: [
      "#0057B8",
      "#00A3E0"
    ],
    hasConsole: true,
    hasLogo: true
  },
  {
    theme: "gba",
    name: "gba",
    fullName: "Game Boy Advance",
    manufacturer: "Nintendo",
    hardwareType: "Portable console",
    releaseYear: 2001,
    total: 72,
    favorites: 18,
    gamesPlayed: 25,
    mostPlayed: "Metroid Fusion",
    description: "The Game Boy Advance is a 32-bit handheld released by Nintendo in 2001, and the last of the Game Boy line.",
    linea: [
      "#5B2C8D",
      "#C0A0E0"
    ],
    hasConsole: true,
    hasLogo: true
  },
  {
    theme: "dreamcast",
    name: "dreamcast",
    fullName: "Sega Dreamcast",
    manufacturer: "Sega",
    hardwareType: "Console",
    releaseYear: 1998,
    total: 27,
    favorites: 6,
    gamesPlayed: 11,
    mostPlayed: "Jet Set Radio",
    description: "The Dreamcast is a 128-bit console released by Sega in 1998, the first of its generation and the first with a built-in modem.",
    linea: [
      "#F26522",
      "#0060A8"
    ],
    hasConsole: true,
    hasLogo: true
  },
  {
    theme: "arcade",
    name: "arcade",
    fullName: "Arcade",
    manufacturer: "Various",
    hardwareType: "Arcade",
    releaseYear: 1979,
    total: 143,
    favorites: 24,
    gamesPlayed: 38,
    mostPlayed: "Metal Slug",
    description: "Coin-operated arcade hardware spanning three decades of dedicated boards and cabinets.",
    linea: [
      "#E8B000",
      "#DF0024"
    ],
    hasConsole: true,
    hasLogo: true
  },
  {
    theme: "auto-favorites",
    name: "favorites",
    fullName: "Favorites",
    manufacturer: "Collections",
    hardwareType: "Collection",
    releaseYear: "",
    total: 92,
    favorites: 92,
    gamesPlayed: 41,
    mostPlayed: "Final Fantasy VII",
    description: "Every game flagged as a favourite, gathered across all systems.",
    linea: [
      "#F3C300",
      "#0070d1"
    ],
    hasConsole: false,
    hasLogo: true,
    hasOverlayArt: false,
    isCollection: true
  }
]

export const GAMES: readonly PsxGame[] = [
  {
    name: "Final Fantasy VII",
    system: "psx",
    rom: "Final Fantasy VII (Disc 1).cue",
    desc: "The Shinra Corporation is draining the planet of its life. Cloud, a mercenary turned eco-warrior, joins a resistance cell and finds the journey ahead will change far more than the fate of one city.",
    publisher: "Squaresoft",
    developer: "Squaresoft",
    releaseyear: 1997,
    genre: "Role playing games",
    stars: 5,
    playerCount: 1,
    region: "eu",
    lang: "en",
    favorite: true,
    cheevos: true,
    multidisc: true,
    playcount: 34,
    gametime: 187200,
    lastplayed: "2 days ago",
    art: "ff7",
    overlay: "Final-Fantasy"
  },
  {
    name: "Gran Turismo",
    system: "psx",
    rom: "Gran Turismo.chd",
    desc: "A racing simulator built around collecting and tuning production cars, with a licence system that gates progression behind driving tests.",
    publisher: "Sony Computer Entertainment",
    developer: "Sony Computer Entertainment",
    releaseyear: 1997,
    genre: "Racing",
    stars: 5,
    playerCount: 2,
    region: "eu",
    lang: "en",
    favorite: true,
    cheevos: true,
    playcount: 12,
    gametime: 43200,
    lastplayed: "1 week ago",
    art: "gt"
  },
  {
    name: "Silent Hill",
    system: "psx",
    rom: "Silent Hill.chd",
    desc: "Harry Mason searches a fog-bound town for his missing daughter, and finds it has been replaced by something else.",
    publisher: "",
    developer: "Team Silent",
    releaseyear: 1999,
    genre: "Survival horror",
    stars: 5,
    playerCount: 1,
    region: "eu",
    lang: "en",
    favorite: false,
    cheevos: true,
    playcount: 5,
    gametime: 18000,
    lastplayed: "3 weeks ago",
    art: "sh"
  },
  {
    name: "Tekken 3",
    system: "psx",
    rom: "Tekken 3.chd",
    desc: "The third entry in the fighting series, widely held to be the strongest of the PlayStation generation.",
    publisher: "Namco",
    developer: "",
    releaseyear: 1998,
    genre: "Fighting",
    stars: 4,
    playerCount: 2,
    region: "eu",
    lang: "en",
    favorite: true,
    cheevos: false,
    playcount: 21,
    gametime: 25200,
    lastplayed: "4 days ago",
    art: "tk3"
  },
  {
    name: "Klonoa: Door to Phantomile",
    system: "psx",
    rom: "Klonoa.chd",
    desc: "A side-scrolling platformer rendered in 3D, in which the player grabs and throws enemies to cross gaps.",
    publisher: "",
    developer: "",
    releaseyear: 1997,
    genre: "Platform",
    stars: 4,
    playerCount: 1,
    region: "eu",
    lang: "en",
    favorite: false,
    cheevos: false,
    playcount: 3,
    gametime: 9000,
    lastplayed: "2 months ago",
    art: "klonoa"
  },
  {
    name: "Vib-Ribbon",
    system: "psx",
    rom: "Vib-Ribbon.chd",
    desc: "A rhythm game that generates its levels from whatever audio CD the player loads.",
    publisher: "Sony Computer Entertainment",
    developer: "NanaOn-Sha",
    releaseyear: 1999,
    genre: "Rhythm",
    stars: 0,
    playerCount: 1,
    region: "eu",
    lang: "en",
    favorite: false,
    cheevos: false,
    playcount: 1,
    gametime: 1800,
    lastplayed: "5 months ago",
    art: "vib"
  },
  {
    name: "Metal Gear Solid",
    system: "psx",
    rom: "Metal Gear Solid (Disc 1).chd",
    desc: "Solid Snake infiltrates a nuclear disposal facility seized by a rogue special forces unit.",
    publisher: "Konami",
    developer: "Konami",
    releaseyear: 1998,
    genre: "Stealth",
    stars: 5,
    playerCount: 1,
    region: "eu",
    lang: "en",
    favorite: true,
    cheevos: true,
    multidisc: true,
    tags: [
      "finished"
    ],
    playcount: 18,
    gametime: 72000,
    lastplayed: "6 days ago",
    art: "mgs",
    overlay: "Metal-Gear"
  },
  {
    name: "Castlevania: Symphony of the Night",
    system: "psx",
    rom: "SOTN.chd",
    desc: "Alucard explores his father's castle in an open, upgrade-driven design that named a genre.",
    publisher: "Konami",
    developer: "Konami",
    releaseyear: 1997,
    genre: "Action adventure",
    stars: 5,
    playerCount: 1,
    region: "eu",
    lang: "en",
    favorite: true,
    cheevos: true,
    tags: [
      "in progress"
    ],
    playcount: 9,
    gametime: 32400,
    lastplayed: "yesterday",
    art: "sotn"
  },
  {
    name: "Bushido Blade",
    system: "psx",
    rom: "Bushido Blade.chd",
    desc: "A weapons fighter with no health bars, in which a single clean strike ends the match.",
    publisher: "Squaresoft",
    developer: "Light Weight",
    releaseyear: 1997,
    genre: "Fighting",
    stars: 3,
    playerCount: 2,
    region: "eu",
    lang: "en",
    favorite: false,
    cheevos: false,
    tags: [
      "buggy"
    ],
    playcount: 2,
    gametime: 3600,
    lastplayed: "3 months ago",
    art: "bushido"
  },
  {
    name: "Crash Bandicoot",
    system: "psx",
    rom: "Crash Bandicoot.chd",
    desc: "A linear 3D platformer built around tight, memorised runs down corridors and along beaches.",
    publisher: "Sony Computer Entertainment",
    developer: "Naughty Dog",
    releaseyear: 1996,
    genre: "Platform",
    stars: 4,
    playerCount: 1,
    region: "eu",
    lang: "en",
    favorite: true,
    cheevos: true,
    tags: [
      "liked"
    ],
    playcount: 15,
    gametime: 28800,
    lastplayed: "1 week ago",
    art: "crash",
    overlay: "Crash-Bandicoot"
  },
  {
    name: "PaRappa the Rapper",
    system: "psx",
    rom: "PaRappa.chd",
    desc: "A rhythm game in paper-thin 2D characters, in which the player answers each teacher's line in time.",
    publisher: "Sony Computer Entertainment",
    developer: "NanaOn-Sha",
    releaseyear: 1996,
    genre: "Rhythm",
    stars: 4,
    playerCount: 1,
    region: "eu,us",
    lang: "en",
    favorite: false,
    cheevos: false,
    kidGame: true,
    hasSaveState: true,
    playcount: 7,
    gametime: 10800,
    lastplayed: "2 weeks ago",
    art: "parappa"
  },
  {
    name: "Point Blank",
    system: "psx",
    rom: "Point Blank.chd",
    desc: "A light-gun game built from short shooting-gallery minigames rather than a continuous stage.",
    publisher: "Namco",
    developer: "Namco",
    releaseyear: 1994,
    genre: "Shooter",
    stars: 3,
    playerCount: 2,
    region: "eu",
    lang: "en,fr,de",
    favorite: false,
    cheevos: false,
    gunGame: true,
    hasKeyboardMapping: true,
    hasManual: true,
    playcount: 0,
    gametime: 0,
    lastplayed: "never",
    art: "pointblank"
  },
  {
    name: "Super Metroid",
    system: "snes",
    rom: "Super Metroid.sfc",
    genre: "Action adventure",
    publisher: "Nintendo",
    developer: "Nintendo R&D1",
    releaseyear: 1994,
    stars: 5,
    desc: "Samus returns to Zebes to recover the last Metroid, in a map-driven adventure that set the template for the genre.",
    art: "metroid",
    playerCount: 1,
    region: "eu",
    lang: "en",
    favorite: false,
    cheevos: false,
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "The Legend of Zelda: A Link to the Past",
    system: "snes",
    rom: "Zelda ALTTP.sfc",
    genre: "Action adventure",
    publisher: "Nintendo",
    developer: "Nintendo EAD",
    releaseyear: 1991,
    stars: 5,
    favorite: true,
    cheevos: true,
    desc: "Link travels between a light world and a dark one to rescue the seven maidens and stop Ganon.",
    art: "zelda",
    overlay: "Zelda",
    playerCount: 1,
    region: "eu",
    lang: "en",
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "Chrono Trigger",
    system: "snes",
    rom: "Chrono Trigger.sfc",
    genre: "Role playing games",
    publisher: "Squaresoft",
    developer: "Squaresoft",
    releaseyear: 1995,
    stars: 5,
    favorite: true,
    desc: "A party travels across eras to prevent a catastrophe, in a role-playing game built around a branching set of endings.",
    art: "chrono",
    playerCount: 1,
    region: "eu",
    lang: "en",
    cheevos: false,
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "GoldenEye 007",
    system: "n64",
    rom: "GoldenEye 007.z64",
    genre: "Shooter",
    publisher: "Nintendo",
    developer: "Rare",
    releaseyear: 1997,
    stars: 5,
    playerCount: 4,
    favorite: true,
    desc: "A first-person shooter adapted from the film, remembered as much for its split-screen multiplayer as its campaign.",
    art: "goldeneye",
    region: "eu",
    lang: "en",
    cheevos: false,
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "Super Mario 64",
    system: "n64",
    rom: "Super Mario 64.z64",
    genre: "Platform",
    publisher: "Nintendo",
    developer: "Nintendo EAD",
    releaseyear: 1996,
    stars: 5,
    cheevos: true,
    desc: "The first 3D Mario, built around open courses and an analogue moveset rather than linear stages.",
    art: "mario64",
    playerCount: 1,
    region: "eu",
    lang: "en",
    favorite: false,
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "Sonic the Hedgehog 2",
    system: "megadrive",
    rom: "Sonic 2.md",
    genre: "Platform",
    publisher: "Sega",
    developer: "Sega Technical Institute",
    releaseyear: 1992,
    stars: 4,
    playerCount: 2,
    favorite: true,
    desc: "Sonic and Tails run through zones built for speed, with a spin dash and a split-screen versus mode.",
    art: "sonic2",
    region: "eu",
    lang: "en",
    cheevos: false,
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "Streets of Rage 2",
    system: "megadrive",
    rom: "Streets of Rage 2.md",
    genre: "Beat em up",
    publisher: "Sega",
    developer: "Sega",
    releaseyear: 1992,
    stars: 5,
    playerCount: 2,
    desc: "A side-scrolling brawler with a widely praised soundtrack.",
    art: "sor2",
    region: "eu",
    lang: "en",
    favorite: false,
    cheevos: false,
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "Metroid Fusion",
    system: "gba",
    rom: "Metroid Fusion.gba",
    genre: "Action adventure",
    publisher: "Nintendo",
    developer: "Nintendo R&D1",
    releaseyear: 2002,
    stars: 5,
    favorite: true,
    cheevos: true,
    desc: "Samus, infected by a parasite, works through a research station under the direction of a ship computer.",
    art: "fusion",
    playerCount: 1,
    region: "eu",
    lang: "en",
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "Advance Wars",
    system: "gba",
    rom: "Advance Wars.gba",
    genre: "Strategy",
    publisher: "Nintendo",
    developer: "Intelligent Systems",
    releaseyear: 2001,
    stars: 4,
    playerCount: 4,
    desc: "A turn-based tactics game played on grid maps with unit production and commanding officers.",
    art: "advwars",
    region: "eu",
    lang: "en",
    favorite: false,
    cheevos: false,
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "Jet Set Radio",
    system: "dreamcast",
    rom: "Jet Set Radio.chd",
    genre: "Action",
    publisher: "Sega",
    developer: "Smilebit",
    releaseyear: 2000,
    stars: 4,
    favorite: true,
    desc: "Inline skaters tag a stylised Tokyo, in the game that popularised cel-shaded rendering.",
    art: "jsr",
    playerCount: 1,
    region: "eu",
    lang: "en",
    cheevos: false,
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "Shenmue",
    system: "dreamcast",
    rom: "Shenmue (Disc 1).chd",
    genre: "Adventure",
    publisher: "Sega",
    developer: "Sega AM2",
    releaseyear: 1999,
    stars: 4,
    multidisc: true,
    desc: "Ryo investigates his father's death across a simulated 1980s Yokosuka.",
    art: "shenmue",
    playerCount: 1,
    region: "eu",
    lang: "en",
    favorite: false,
    cheevos: false,
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "Metal Slug",
    system: "arcade",
    rom: "mslug.zip",
    genre: "Run and gun",
    publisher: "SNK",
    developer: "Nazca",
    releaseyear: 1996,
    stars: 5,
    playerCount: 2,
    favorite: true,
    cheevos: true,
    desc: "A hand-animated run-and-gun built around rescuing prisoners and commandeering vehicles.",
    art: "mslug",
    region: "eu",
    lang: "en",
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  },
  {
    name: "Street Fighter II",
    system: "arcade",
    rom: "sf2.zip",
    genre: "Fighting",
    publisher: "Capcom",
    developer: "Capcom",
    releaseyear: 1991,
    stars: 5,
    playerCount: 2,
    desc: "The fighting game that defined the genre and the arcade competitive scene.",
    art: "sf2",
    region: "eu",
    lang: "en",
    favorite: false,
    cheevos: false,
    playcount: 4,
    gametime: 12600,
    lastplayed: "2 weeks ago"
  }
]
